Première version de la traduction française de "Detecting Text Reuse with Passim"
programminghistorian/ph-submissions pull request #369
Opened 2021-04-26 15:56 UTC by camaya28

(Voir #334)

2021-04-27 05:43 UTC, spapastamkou requested changes
Bonjour, serait-il possible de renommer le fichier de la traduction sans utiliser d'accents pour éviter d'éventuels soucis? Cela pourrait avoir la forme suivante: detecter-la-reutilisation-de-texte-avec-passim.md 
Merci!

2021-04-28 21:36 UTC, mromanello commented
@spapastamkou Le fichier a été renommé par @camaya28. Faites nous savoir s'il y a besoin d'autres modifications.

2021-04-30 09:40 UTC, spapastamkou approved these changes

2021-04-30 09:41 UTC, merged

2021-04-30 09:44 UTC, spapastamkou commented
Le fichier est maintenant dans le dépôt. Nous vous tiendrons informés lorsque l'équipe sera en mesure d'organiser la relecture de la traduction. Merci beaucoup!