Copyedit analisis redes sociales teatro 1
programminghistorian/ph-submissions pull request #586
Opened 2023-09-05 14:05 UTC by jamotilla

2023-09-05 14:15 UTC, jamotilla commented on es/borradores/originales/analisis-redes-sociales-teatro-1.md
> +Dice Miguel Escobar Varela en su reciente libro *Theater as Data* (2021), que el teatro depende de relaciones (p. 94). Las relaciones entre intérpretes y público dan lugar al hecho teatral como acto
Ya que el sistema de referencia que utilizamos es “Notas y Bibliografía” que se encuentra en el [Manual Chicago 17a edición](https://uc3m.libguides.com/guias_tematicas/citas_bibliograficas/chicago), es mejor que la referencia al documento y a la página lo hagas en una nota al pie. Por favor revisa las referencias en todo el documento.

2023-09-05 14:15 UTC, jamotilla commented on es/borradores/originales/analisis-redes-sociales-teatro-1.md
> +   1.1 Por norma general, cada intervención marcada en el texto equivale a una interacción, y esta interacción puede tener uno o varios receptores:
Por favor revisa la numeración que te sugiero, creo que es mucho más clara

2023-09-05 14:21 UTC, jamotilla commented
Hola @dxvidmr y @jenniferisasi, he terminado la primer revisión del copyedit. El archivo está disponible en la pestaña "files changed", en la que dejé un par de comentarios. Cualquier duda o sugerencia estoy al pendiente. 
Saludos, J A

2023-09-20 19:26 UTC, dxvidmr requested changes

2023-09-20 19:26 UTC, dxvidmr commented on es/borradores/originales/analisis-redes-sociales-teatro-1.md
> +Según el criterio de la interacción lingüística directa entre personajes, dos actores están relacionados si hablan entre sí, por lo que se anota y cuantifica cada vez que un personaje se dirige a otr
No me convence el uso del término "actores" aquí, creo que puede hacer pensar en los actores en tanto que representantes y entraríamos en la dimensión de la representación, que no interesa aquí. Sugiero esta redacción para evitar la repetición de "personajes": 

_Según el criterio de la interacción lingüística directa entre personajes, estos están relacionados si hablan entre sí, por lo que se anota y cuantifica cada vez que un personaje se dirige a otro._

2023-09-20 19:26 UTC, dxvidmr commented on es/borradores/originales/analisis-redes-sociales-teatro-1.md
> +Los grafos pueden ser de dos tipos: no dirigidos, cuando la relación entre los elementos del sistema es siempre bidireccional en igualdad de condiciones o la direccionalidad no es relevante; y dirigi
Corregida errata en "aunque"

2023-09-20 19:26 UTC, dxvidmr commented on es/borradores/originales/analisis-redes-sociales-teatro-1.md
>  # Notas
Añadidas en notas las referencias que estaban citadas en el texto.

2023-09-20 19:26 UTC, dxvidmr commented on es/borradores/originales/analisis-redes-sociales-teatro-1.md
> +# Bibliografía
Añadidas en la ahora "Bibliografía" algunas referencias que estaban en notas pero no aquí. He modificado algo el formato siguiendo Chicago17 (estaban exportadas así de Zotero pero alguna cosa no coincidía con el recurso indicado).

2023-09-20 19:29 UTC, dxvidmr commented
He hecho las modificaciones y dejado un par de cometarios, ¡espero haberlo hecho bien! Cualquier cosa, quedo pendiente. ¡Gracias!

2023-09-21 10:59 UTC, anisa-hawes commented
Brilliant! Many thanks, @dxvidmr! 

@jamotilla will review your comments and edits, then mark these conversations as resolved 🙂

2023-09-23 01:25 UTC, jamotilla commented on es/borradores/originales/analisis-redes-sociales-teatro-1.md
> +Según el criterio de la interacción lingüística directa entre personajes, dos actores están relacionados si hablan entre sí, por lo que se anota y cuantifica cada vez que un personaje se dirige a otr
De acuerdo @dxvidmr !

2023-09-23 01:36 UTC, merged

2023-09-23 01:40 UTC, jamotilla commented
Hi @anisa-hawes, this lesson is ready! Thanks everyone for your hard work!