Copyedit concevoir recherche donnees nodegoat
programminghistorian/ph-submissions pull request #597
Opened 2024-01-17 14:36 UTC by charlottejmc

I am preparing to merge my copyedits of the FR lesson #459 concevoir-recherche-donnees-nodegoat.

2024-01-17 14:39 UTC, charlottejmc commented
Hello @digitalkosovski and @spapastamkou. 

I've now prepared the copyedits for this lesson. I'd be grateful if you could review the adjustments and confirm that you are happy for me to merge these. You can see the details of my edits under the [files changed](https://github.com/programminghistorian/ph-submissions/pull/597/files) tab!

I'd like to bring your attention to the comments I have attached to certain specific lines. You can respond to any of my suggestions via the comments below, or click _Resolve conversation_ if you're happy with them like this:

![image](https://github.com/programminghistorian/jekyll/assets/143802849/6a73acb9-215d-4fe1-8ab7-247921a3e6a4)

If you want to make edits, please work by navigating to the [files changed](https://github.com/programminghistorian/ph-submissions/pull/597/files) and clicking the three dots at the upper right of the file, then _Edit file_:

<img width="1409" alt="image" src="https://github.com/programminghistorian/ph-submissions/assets/143802849/54d8ad50-31b6-4cad-a71f-3248721b4d55">

2024-01-17 14:43 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +title: "Construire une base de données pour les sciences humaines avec nodegoat"
J'ai trouvé le titre proposé un peu vague/confus. Je me demande s'il n'y aurait pas une façon plus claire et succincte d'exprimer le contenu et l'objectif de la leçon. Dans notre index de leçons, on voit une tendance à commencer avec un verbe (&laquo;&nbsp;constuire&nbsp;&raquo;). J'ai proposé cette alternative, mais n'hésitez pas à l'adapter si vous préférez autre chose (et si vous êtes d'accord qu'on pourrait améliorer la version actuelle).

2024-01-17 14:58 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
>  ## Entre le modèle et la base de données
Sans réorganiser le texte, j'ai introduit des titres pour le découper en sections un peu plus courtes, et mieux remplir la table des matières. J'ai proposé :
```
## Introduction : penser en termes de données, un défi conceptuel

## Entre le modèle et la base de données

  ### Le tableur simple
 
  ### La base de données relationnelle

  ### Le modèle de données

## Construire une base de données avec nodegoat

  ### Démarrer avec nodegoat
  
  ### Mettre en place son projet dans nodegoat
 
    #### Définir les objets du modèle

    #### Paramétrer le modèle de données

    #### Explorer et exploiter le modèle de données

## Conclusion
```

Je ne suis toujours pas tout à fait convaincue par le titre de la section `## Entre le modèle et la base de données`, car je ne crois pas qu'il exprime clairement l'idée de cette section. Est-ce qu'on pourrait le reformuler ?

2024-01-17 15:04 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Désormais, le type d'objet **Maison d’Edition** comporte un attribut différent d'**Auteur** et d'**Ouvrage**, qui permet d’introduire des informations temporelles en tant qu'intervalles de temps.
Cette étape laisse à penser qu’il aurait fallu effacer l’attribut ‘date de fondation’ de l’objet Maison d’Edition, pour ne garder que ce sous-objet. Est-ce une étape à rajouter brièvement plus haut ? Peut-être que je me trompe, et qu'il est en effet nécessaire de garder les deux versions ! Dans les deux cas, rajoutons peut-être une courte explication ?

2024-01-17 15:10 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Nous pouvons aussi importer l’ensemble de nos données après la fin du dépouillement de nos sources, à l’aide de fichiers CSV, plutôt que les enregistrer manuellement au fur et à mesure.
J'ai été étonnée par la brièveté de cette phrase, car elle ne donne aucun détail sur comment faire ! Les explications jusqu'ici ont été si détaillées que le contraste est surprenant. A la ligne 171 (vert), on nous dit que cette leçon va &laquo;&nbsp;expliquer comment exporter et importer ces données de manière simple et, enfin, de produire des visualisations telles que cartes ou réseau&nbsp;&raquo;. Est-ce que cela vaudrait la peine de rajouter quelques phrases pour décrire le procédé ? Je ne me rends pas bien compte – c'est peut-être très évident en pratique.

2024-01-23 10:18 UTC, digitalkosovski commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +title: "Construire une base de données pour les sciences humaines avec nodegoat"
Le premier titre me semble plus adéquat, car l'objectif de la leçon n'est pas seulement technique, mais aussi conceptuel : il s'agit de développer une réflexion sur comme se déroule la production de données structurées à partir des sources.

Cela dit, je comprends tout à fait la remarque de style, je préfère donc laissé le choix ultime aux éditeurs et notamment à @spapastamkou

2024-01-23 10:22 UTC, digitalkosovski commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
>  ## Entre le modèle et la base de données
D'accord pour les titres, et merci pour ce travail !

Pour le titre ## Entre le modèle et la base de données, d'accord qu'il n'est pas très clair. Peut-être tout simplement ## Le modèle et la base de données ?

2024-01-23 10:32 UTC, digitalkosovski commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Nous pouvons aussi importer l’ensemble de nos données après la fin du dépouillement de nos sources, à l’aide de fichiers CSV, plutôt que les enregistrer manuellement au fur et à mesure.
Si je me souviens bien, on ne dit pas dans la leçon que l'on va « expliquer comment exporter et importer ces données de manière simple et, enfin, de produire des visualisations telles que cartes ou réseau ». Le texte dit : 

"Comme nous allons le constater, il permet de concevoir un modèle de données de manière flexible; de gérer et conserver des données en ligne; d’introduire des informations historiques ayant un certain degré d’incertitude; d’exporter et importer ces données de manière simple et, enfin, de produire des visualisations telles que cartes ou réseaux."

Il s'agissait donc d'expliquer que le logiciel offre la possibilité d'exporter et importer ces données, mais sans entrer dans le détail de ces opérations, qui ne sont pas au cœur du sujet de la leçon (la conception d'une recherche en termes de données et la production d'une base de données). 

Personnellement, j'avais décidé de ne pas rentrer dans le détail de l'import de données, car cela voudrait dire aussi discuter de comment faire un bon fichier CSV. Il me semblait donc que l'on finirait par dépasser largement les limites de l'instrument _nodegoat_ et que la leçon deviendrait trop longue et compliquée. 

A ce stade, je pense que c'est mieux de ne pas changer ce point, mais je reste dans l'attente de l'avis de @spapastamkou

2024-01-23 10:36 UTC, digitalkosovski commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Désormais, le type d'objet **Maison d’Edition** comporte un attribut différent d'**Auteur** et d'**Ouvrage**, qui permet d’introduire des informations temporelles en tant qu'intervalles de temps.
En effet, vous avez raison ! Merci pour cette remarque.

Il faut effacer l'attribut "Date de fondation", que nous avons remplacé par le sous-object chronologique. Voulez-vous ajouter une phrase à ce sujet, ou dois-je intervenir moi-même dans le fichier pour le faire ?

2024-01-23 10:37 UTC, digitalkosovski commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Désormais, le type d'objet **Maison d’Edition** comporte un attribut différent d'**Auteur** et d'**Ouvrage**, qui permet d’introduire des informations temporelles en tant qu'intervalles de temps.
En effet, vous avez raison ! Merci pour cette remarque.

Il faut effacer l'attribut "Date de fondation", que nous avons remplacé par le sous-object chronologique. Voulez-vous ajouter une phrase à ce sujet, ou dois-je intervenir moi-même dans le fichier pour le faire ?

2024-01-24 11:52 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Nous pouvons aussi importer l’ensemble de nos données après la fin du dépouillement de nos sources, à l’aide de fichiers CSV, plutôt que les enregistrer manuellement au fur et à mesure.
Merci pour l'explication @digitalkosovski, je comprends mieux la décision de ne pas rentrer dans les détails !

2024-01-24 11:53 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Désormais, le type d'objet **Maison d’Edition** comporte un attribut différent d'**Auteur** et d'**Ouvrage**, qui permet d’introduire des informations temporelles en tant qu'intervalles de temps.
Pas de souci – je m'en charge. Merci !

2024-01-24 14:30 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +title: "Construire une base de données pour les sciences humaines avec nodegoat"
Je comprends le désir d'y intégrer l'aspect conceptuel de la leçon et j'aimerais bien pouvoir le faire ressortir aussi. Peut-être quelque chose dans cette veine ?

- Schématiser (ou Modéliser ?) sa recherche avec nodegoat : concepts fondamentaux pour construire une base de données en sciences humaines

Je laisse aussi la parole à @marie-flesch et @spapastamkou.

2024-01-24 14:49 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
>  ## Entre le modèle et la base de données
Si le titre que j'ai suggéré plus haut vous plait, pourquoi pas le reprendre de la sorte:

## Modéliser sa base de données
[...]
## Construire une base de données avec nodegoat

Ainsi les deux sections reprennent plus au moins la structure du titre de la leçon. 

À discuter, bien sûr !

2024-02-02 11:41 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Transformer une recherche en données implique un certain travail de traduction&nbsp;: il faut traduire nos informations depuis leur forme de base à une forme structurée. La donnée, contrairement à ce
Transformer une recherche en données => mettre en données l'objet d'une recherche

2024-02-02 13:47 UTC, spapastamkou requested changes
Coucou @charlottejmc ! Un grand merci pour ton travail et tes suggestions. Normalement j'ai commenté tout et ai aussi ajouté davantage de commentaires sur certaines parties avec certaines modifications que je suggère. J'ai essayé d'être concise, et si jamais qqch n'est pas clair, n'hésite pas à me solliciter.

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Celles et ceux qui font de la recherche en sciences humaines recontrent souvent des problèmes à ce stade, car la notion même de &laquo;&nbsp;donnée&nbsp;&raquo; n'est pas limpide. En histoire, en ant
recontrent => rencontrent

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Dans cette leçon, nous discuterons des difficultés auxquelles on est susceptible de se confronter au moment de concevoir une base de données dans le cadre d'une recherche en sciences humaines, en tan
en tant débutant => en tant **que** débutant (?)

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +**Table 1 : Ouvrages**
Il faut rétablir "ouvrage" ici (ou tout au plus "Ouvrage"): c'est une convention pour le nommage des tables d'une base de données, d'utiliser les termes au singlulier et en minuscules (même si comme partout il peut y avoir des débats). Mais appliquer le pluriel ici est susceptible de désorienter dans le sens que les images de la leçon utilisent le terme au singulier.

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +**Table 2 : Auteurs**
même chose que pour l. 31

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +**Table 3 : Maisons d’Edition**
Même chose que pour l. 31

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +nodegoat offre en plus deux types d'objets pré-enregistrés, que nous pouvons ici choisir d'utiliser ou non: &laquo;&nbsp;City&nbsp;&raquo; (ville) et &laquo;&nbsp;Geometry&nbsp;&raquo; (géométrie). *
d'utiliser ou non: => encoder une espace insécable avant ":"

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Notre modèle, ses types d'objets et leurs relations sont maintenant définies. Si nous revenons sur l'onglet **Management** et cliquons sur le nom du projet, nodegoat nous montre une visualisation du
Notre modèle, ses types d'objets et leurs relations sont maintenant définies. => *il me semble y avoir un souci dans l'accord de genre entre adjectif et noms, merci infiniment s'il est possible de vérifier à nouveau* 
Idée d'une alternative possible si besoin: Notre modèle est maintenant implémenté, puisque nous avons défini les types d'objets et les relations qui les relient.

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Transformer une recherche en données implique un certain travail de traduction&nbsp;: il faut traduire nos informations depuis leur forme de base à une forme structurée. La donnée, contrairement à ce
(parce qu'une recherche a plusieurs facettes qui peuvent se transformer en données, ici c son objet et la mise en données de ce dernier qui nous intéresse)

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Une fois que nous aurons enregistré tous les ouvrages, auteurs et maisons d’éditions, la base de données ressemblera aux images ci-dessous. Il suffira alors de cliquer sur chaque élément pour accéder
la base de données ressemblera aux images ci-dessous => l'interface d'accès à la base de données ressemblera aux images ci-dessous
(alterantives: interface utilisateur de la bdd, interface de consultation de la bdd...)

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +Nous pouvons aussi importer l’ensemble de nos données après la fin du dépouillement de nos sources, à l’aide de fichiers CSV, plutôt que les enregistrer manuellement au fur et à mesure.
Merci pour la remarque, mais à ce stade-ci il n'y a pas d'ajout à faire dans le texte de la leçon (enfin, normalement:)),. Ce n'est pas un problème pour son efficacité, sinon cela aurait été relevé lors de la phase d'évaluation (les deux évaluateurs ont une expérience d'enseignement en classe).

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +title: "Construire une base de données pour les sciences humaines avec nodegoat"
Le titre suit la logique de celui de la leçon de Marten Düring sur l'analyse de réseaux: [From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources](https://programminghistorian.org/en/lessons/creating-network-diagrams-from-historical-sources)
C'est une des toutes premières questions que j'ai examiné (sous ma casquette de rédactrice en charge du suivi) avec l'auteur lors de la phase de vérification éditoriale et avant l'évaluation, et nous en avons discuté sur le ticket et par mail. Notre but n'était pas de "vendre" la leçon comme un tutoriel pour constuire une bdd avec le logiciel en question (il peut y en avoir qui sont plus complets du point de vue technique), mais de pourvoir aux besoins d'un(e) novice, voire qui soit historien(e). D'où l'association des mots "sources" et "données" et "nodegoat", pour que la leçon soit pertinemment indexée sur le web pour le public que nous visons. Le titre idéal serait "Des sources aux données historiques, concevoir une base de données à l'aide de nodegoat" ou "Des sources aux données, concevoir une base de données en shs avec nodegoat" mais je l'avais exclu (de mémoire) à cause de la redondance du mot "données" qui n'est pas tolérée, de ce que je sais, en français. Si à ton avis cette formulation n'est pas prohibitive, nous pouvons modifier en ce sens (à condition que @digitalkosovski soit d'accord). Au cas contraire, il serait préférable de garder le titre comme il était. Merci beaucoup pour ton oeil attentif et tes suggestions!

2024-02-02 13:47 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
>  ## Entre le modèle et la base de données
```
## De la saisie à la modélisation de données
  ### Saisie simple de données tabulaires 
  ### Du tableur à la base de données: les principes de modélisation *(de données) si redondance tolérée)*
```
(sans 3e partie distinguée ici)

Pour la partie base: aucun problème de garder ces titres-ci en modifiant ceux qui existent: 
```
## Construire une base de données avec nodegoat
 ### Démarrer avec nodegoat
 ### Mettre en place son projet dans nodegoat
```
Pour les niveaux 4: 
- Normalement on n'utilise pas de titres qui vont au delà du niveau 3 en profondeur (cela faisait partie des consignes aux auteurs à une époque), même s'il n'est pas exclu d'avoir pêché dans certaines leçons par le passé. 
- La leçon n'a pas vraiment été écrite dans une logique de distinction de parties et il peut y avoir des A/R de l'une à l'autre 

Donc, si les niveaux 4 sont à garder, puisque @digitalkosovski est d'accord, on va: 
- les transformer en niveau 3   
- surtout, remplacer dans ces titres "modèle de données" avec "base de données". Le modèle de données et son abstraction sont traités à la précédente partie, ici on est dans son implémentation via la bdd, et c'est la bdd qui est l'objet de toutes les opérations décrites.

2024-02-02 13:48 UTC, spapastamkou commented
(@charlottejmc tu verras les mêmes commentaires à deux reprises, désolée:))

2024-02-02 15:05 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
>  ## Entre le modèle et la base de données
Merci beaucoup pour ces suggestion qui me paraissent très adaptés ! 

Dans les consignes de [Typesetting](https://github.com/programminghistorian/jekyll/wiki/Typesetting#headings) développées avec Anisa, pourtant, on a décidé d'accepter les titres de niveaux 2 à 4. Je trouve que ça marche plutôt bien ici dans une optique de guider les lectrices/eurs à travers la démarche, d'abord théorique puis pratique. J'ai donc pour l'instant repris tes suggestions de titres, mais gardé les même niveaux...

2024-02-02 15:19 UTC, charlottejmc commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +title: "Construire une base de données pour les sciences humaines avec nodegoat"
En effet, c'est assez délicat ! Je vois la logique inspirée de &laquo;&nbsp;From Hermeneutics to Data to Networks&nbsp;&raquo;, ou d'ailleurs &laquo;&nbsp;From HTML to List of Words&nbsp;&raquo;, qui a été traduite en français : &laquo;&nbsp;Du HTML à une liste de mots&nbsp;&raquo;... Je crois que cette formulation marche vraiment bien en anglais, mais qu'elle perd malheureusement un peu son sens en français, et (selon moi) qu'elle n'exprime pas aussi clairement qu'on le voudrait ce réel &laquo;&nbsp;passage&nbsp;&raquo; **de** X **à** Y. 

Peut-être qu'on pourrait tout de même commencer par un verbe qui fait ressortir cette évolution ?

- Passer des sources aux données : concevoir une base de données en sciences humaines avec nodegoat
- Transformer ses sources en données : concevoir une base de données en sciences humaines avec nodegoat
- Passer des sources aux données avec nodegoat : la conceptualisation d'une base de données en sciences humaines
Ou encore...
- Modéliser ses sources dans nodegoat : concepts fondamentaux pour construire une base de données en sciences humaines (pour utiliser le terme &laquo;&nbsp;sources&nbsp;&raquo;)

Mais je te laisse bien sûr le dernier mot 😄

2024-02-02 15:23 UTC, charlottejmc commented
Merci beaucoup @spapastamkou pour tes commentaires vraiment détaillés et réfléchis ! J'apprécie ton expertise en HN qui a pu faire ressortir les quelques erreurs que j'avais introduites 😬 J'ai laissé deux commentaires à propos des titres, mais je crois qu'on arrive bientôt à bout !

2024-02-07 16:35 UTC, anisa-hawes commented
Thank you @charlottejmc, @digitalkosovski and @spapastamkou.

I think I agree with Charlotte about the title. In my view, effective lesson titles often start with an active verb. The key thing is discoverability (both through online search towards our website, and within our lesson directories). I would like to suggest that a combination of two of Charlotte's proposed alternative titles might be worth consideration:

_Transformer ses sources en données : la conceptualisation d'une base de données en sciences humaines avec nodegoat_

Translating your conversations above, I understand you are also in discussion about the section and sub-section structure. This aspect will (of course) have an impact upon readers' initial encounter with this lesson, because the table of contents is one of the first things they will read. If the table of contents is clear, easy-to-follow, and defines meaningful signposts through the lesson it can be an important navigation tool. 

I am sure @marie-flesch will want to take a view on both the title + the section structure, and make the final decision when she does her thorough read-through pre-Publication. 

But for now, I think this PR can be merged. Charlotte and I will move onwards to typesetting and creation of archival links, before handing over to Marie with the questions raised above. 

Thanks to all.
Anisa

2024-02-07 16:42 UTC, merged

2024-02-08 09:25 UTC, spapastamkou commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +title: "Construire une base de données pour les sciences humaines avec nodegoat"
Bonjour @charlottejmc et merci pour ta persévérance: le titre 2, parmi tes nouvelles propositions, correspond le plus à l'approche et au contenu de la leçon, ainsi qu'aux échanges avec l'auteur. Merci donc de retenir le titre suivant come titre final de la leçon: "Des sources aux données, concevoir une base de données en sciences humaines et sociales avec nodegoat".
Pour information, et pour dissiper tout doute qui pourrait persister à propos de l'absence de verbe et la pertinence de la formulation, voici quelques exemples [ici](https://www.cairn.info/methodes-quantitatives-pour-l-historien--9782707153401-page-34.htm), ou encore [là](https://orbilu.uni.lu/handle/10993/51072): la formulation est bien ancrée dans la bibliographie courante et reconnaissable par la communauté à laquelle la leçon s'adresse.

2024-02-08 09:32 UTC, spapastamkou commented
@anisa-hawes Thank you for your thoughts. I just commented for the title; as for the subsections suggestion, these have been validated by the author; my question was about the level - I did not know we had level 4 accepted now. I believe all the pending questions have been resolved and the lesson should be ready after Charlotte's final work and Marie's final editorial controls. Thanks all for your work.

2024-02-23 09:28 UTC, marie-flesch commented on fr/en-cours/originales/concevoir-recherche-donnees-nodegoat.md
> +title: "Construire une base de données pour les sciences humaines avec nodegoat"
J'approuve le titre "Des sources aux données, concevoir une base de données en sciences humaines et sociales avec nodegoat" proposé par @spapastamkou , il me semble clair et refléter le contenu de la leçon ! (et merci pour cette très intéressante discussion :)